# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /apikeys/{id}_delete for http method type DELETE 
# RoostTestHash=4affc26394
# 
# 

# ********RoostGPT********
Feature: API keys management

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def AuthHeader = { ApiKeyAuth: '#(authToken)' }

  Scenario Outline: Get API key details with valid UUID
    Given path '<id>'
    And headers AuthHeader
    When method get
    Then status 200
    And match responseHeaders['api-version'][0] == '1.0.0'
    And match each response == { id: '#uuid', name: '#string', created_at: '#string', last_used_at: '#string?' }

    Examples:
      | read('apikeys_id_delete.csv') |

  Scenario Outline: Get API key details with invalid UUID should return 400 Bad Request
    Given path '<id>'
    And headers AuthHeader
    When method get
    Then status 400
    And match responseHeaders['api-version'][0] == '1.0.0'
    And match response == { error: '#string', description: 'Descriptive Error Message' }

    Examples:
      | id    |
      | 12345 |

  Scenario: Get API key details without authentication should return 401 Authentication Required
    Given path '3fa85f64-5717-4562-b3fc-2c963f66afa6'
    When method get
    Then status 401
    And match responseHeaders['api-version'][0] == '1.0.0'
    And match response == { error: '#string', description: 'Descriptive Error Message' }
