# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /apikeys_get for http method type GET 
# RoostTestHash=9e57a3b0dd
# 
# 

# ********RoostGPT********
Feature: List API Keys

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authHeader = { 'Authorization': '#(karate.properties[''AUTH_TOKEN''])' }

  Scenario: Successful retrieval of API Keys
    Given path '/apikeys'
    And headers authHeader
    When method get
    Then status 200
    And match responseHeaders contains { 'api-version': '#string' }
    And match response == { total: '#number', apikeys: '#array' }

  Scenario: Retrieval of API Keys with Bad Request
    Given path '/apikeys'
    And headers authHeader
    And param invalidParam = 'invalid'
    When method get
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        "error": "#string",
        "description": "#string"
      }
      """

  Scenario: Retrieval of API Keys without Authorization
    Given path '/apikeys'
    When method get
    Then status 401
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        "error": "#string",
        "description": "#string"
      }
      """
