# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /authorizations_post for http method type POST 
# RoostTestHash=ed8c1b7bff
# 
# 

# ********RoostGPT********
Feature: Authorize another existing Account to access my Account

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario Outline: Authorize an account with valid email
    Given path '/authorizations'
    And request
      """
      { 
        "email": "<email>" 
      }
      """
    When method post
    Then status 201
    And match responseHeaders contains { 'api-version': '#string', 'location': '#string' }
    And match response ==
      """
      { 
        "id": "#uuid", 
        "name": "#? _ != null", 
        "email": "<email>", 
        "createdAt": "#string", 
        "updatedAt": "#string" 
      }
      """

    Examples:
      | read('authorizations_post.csv') |

  Scenario: Attempt to authorize an account with invalid email
    Given path '/authorizations'
    And request
      """
      { 
        "email": "invalid-email" 
      }
      """
    When method post
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      { 
        "error": "#string", 
        "description": "Descriptive Error Message" 
      }
      """

  Scenario: Authorize an account without authentication token
    * header ApiKeyAuth = ''
    Given path '/authorizations'
    And request
      """
      { 
        "email": "test@example.com" 
      }
      """
    When method post
    Then status 401
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      { 
        "error": "#string", 
        "description": "Descriptive Error Message" 
      }
      """
