# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /authorizations/{id}_delete for http method type DELETE 
# RoostTestHash=cb128291e8
# 
# 

# ********RoostGPT********
Feature: Remove Authorized Account by ID

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario Outline: Delete an authorized account with valid UUID
    Given path 'authorizations', '<id>'
    When method delete
    Then status 200
    And match header api-version == '1.0.0'

    Examples:
      | read('authorizations_id_delete.csv') |

  Scenario Outline: Delete an authorized account with invalid UUID should result in Bad Request
    Given path 'authorizations', '<id>'
    When method delete
    Then status 400
    And match header api-version == '1.0.0'
    And match response == { error: '#string', description: 'Descriptive Error Message' }
    And match response.error contains 'error/code'

    Examples:
      | id           |
      | invalid-uuid |

  Scenario Outline: Delete an authorized account without proper authentication should fail
    Given path 'authorizations', '<id>'
    And header ApiKeyAuth = null
    When method delete
    Then status 401
    And match header api-version == '1.0.0'
    And match response == { error: '#string', description: 'Descriptive Error Message' }
    And match response.error contains 'error/code'

    Examples:
      | id                                   |
      | 123e4567-e89b-12d3-a456-426614174000 |
