# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /errors_get for http method type GET 
# RoostTestHash=588ae64bad
# 
# 

# ********RoostGPT********
Feature: Testing /errors endpoint for various HTTP methods

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario: GET /errors - Successful operation with 200 response code
    Given path '/errors'
    When method get
    Then status 200
    And match header api-version == '1.0.0'
    And match each response contains { description: '#string', error: '#string' }

  Scenario Outline: GET /errors - Successful operation with 200 response code and validation errors
    Given path '/errors'
    When method get
    Then status 200
    And match header api-version == '1.0.0'
    And match each response contains { description: '#string', error: '#regex[^validation/.*$]', schema_field: '#string', value: '##any' }

  Scenario Outline: GET /errors - Successful operation with 200 response code and specific error
    Given path '/errors'
    When method get
    Then status 200
    And match response contains { description: '<description>', error: '<error>' }

    Examples:
      | read('errors_get.csv') |
