# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /kvk/zoeken_get for http method type GET 
# RoostTestHash=2acea70323
# 
# 

# ********RoostGPT********
Feature: KvK Zoeken API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { ApiKeyAuth: '#(authToken)' }

  Scenario Outline: Test KvK Zoeken API with different query parameters
    Given path '/kvk/zoeken'
    And param kvkNummer = '<kvkNummer>'
    And param vestigingsnummer = '<vestigingsnummer>'
    And param handelsnaam = '<handelsnaam>'
    When method get
    Then status 200
    And match response == '<expectedResponse>'

    Examples:
      | read('kvk_zoeken_get.csv') |
