# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /login_post for http method type POST 
# RoostTestHash=3122292ee3
# 
# 

# ********RoostGPT********
Feature: Login using OTP to create a session

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Login with valid email, otp, and client type to receive a session token
    Given path '/login'
    And request
      """
      { 
        email: '<email>', 
        otp: '<otp>', 
        client: '<client>' 
      }
      """
    When method post
    Then status 201
    And match response contains
      """
      { 
        token: '#regex ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' 
      }
      """
    And match header api-version == '1.0.0'

    Examples:
      | read('login_post.csv') |

  Scenario Outline: Login with invalid email pattern should return 400 Bad Request
    Given path '/login'
    And request
      """
      { 
        email: '<email>', 
        otp: '123456', 
        client: 'mobile' 
      }
      """
    When method post
    Then status 400
    And match response ==
      """
      { 
        error: '#regex ^validation/.*$', 
        description: 'Descriptive Error Message' 
      }
      """
    And match header api-version == '1.0.0'

    Examples:
      | email               |
      | 'invalidemail'      |
      | 'user@.com'         |
      | 'user@@example.com' |
      | 'user@example'      |

  Scenario Outline: Login with missing required fields should return 400 Bad Request
    Given path '/login'
    And request <body>
    When method post
    Then status 400
    And match response ==
      """
      { 
        error: 'error/code', 
        description: 'Descriptive Error Message' 
      }
      """
    And match header api-version == '1.0.0'

    Examples:
      | body                                            |
      | { email: 'user@example.com' }                   |
      | { otp: '123456' }                               |
      | { client: 'mobile' }                            |
      | { email: 'user@example.com', otp: '123456' }    |
      | { email: 'user@example.com', client: 'mobile' } |
      | { otp: '123456', client: 'mobile' }             |
