# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /logout_post for http method type POST 
# RoostTestHash=64d33906e5
# 
# 

# ********RoostGPT********
Feature: Logout API feature

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario: Successful logout with valid credentials
    Given path '/logout'
    When method delete
    Then status 200
    And match header api-version == '1.0.0'

  Scenario Outline: Logout with invalid credentials leading to bad request
    Given path '/logout'
    And request
      """
      <requestBody>
      """
    When method delete
    Then status 400
    And match header api-version == '1.0.0'
    And match response
      """
      <expectedResponse>
      """

    Examples:
      | requestBody                                                        | expectedResponse                                                               |
      | { "description": "Missing token", "error": "error/token-missing" } | { "description": "Descriptive Error Message", "error": "error/token-missing" } |
      | { "description": "Invalid token", "error": "error/invalid-token" } | { "description": "Descriptive Error Message", "error": "error/invalid-token" } |
