# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /recipients/branches/{id}_get for http method type GET 
# RoostTestHash=061355b093
# 
# 

# ********RoostGPT********
Feature: Recipient Branch API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Get recipient branch details by ID with valid UUID
    Given path 'recipients/branches', '<id>'
    And header ApiKeyAuth = authToken
    When method get
    Then status 200
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        cocBranchNumber: '#regex(\\d{12})',
        cocNumber: '#regex(\\d{8})',
        createdAt: '#string',
        deregistrationDate: '##string',
        eoriNumber: '##regex(NL\\d{9})',
        id: '#uuid',
        tradeName: '#string',
        tradeNames: '#array',
        updatedAt: '#string'
      }
      """

    Examples:
      | read('recipients_branches_id_get.csv') |

  Scenario: Get recipient branch details with invalid UUID
    Given path 'recipients/branches', 'invalid-uuid'
    And header ApiKeyAuth = authToken
    When method get
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        error: '#string',
        description: '#string'
      }
      """

  Scenario: Get recipient branch details without authorization token
    Given path 'recipients/branches', '123e4567-e89b-12d3-a456-426614174000'
    When method get
    Then status 401
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        error: '#string',
        description: '#string'
      }
      """
