# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /recipients/branches_put for http method type PUT 
# RoostTestHash=63322ffb26
# 
# 

# ********RoostGPT********
Feature: Recipient Branch API

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario Outline: Add new branch with valid details
    Given path '/recipients/branches'
    And request <body>
    When method post
    Then status <expectedStatus>
    And match responseHeaders contains { 'api-version': '#string', 'location': '#string' }
    And match response == <expectedResponse>

    Examples:
      | read('recipients_branches_put.csv') |

  Scenario: Add new branch with invalid email format
    Given path '/recipients/branches'
    And request
      """
      { 
        "cocNumber": "12345678", 
        "tradeName": "KarateMart", 
        "email": "not-an-email" 
      }
      """
    When method post
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      { 
        "error": "validation/email-pattern", 
        "description": "Descriptive Error Message", 
        "value": "not-an-email", 
        "field": "email", 
        "schema_field": "email" 
      }
      """

  Scenario: Add new branch without required field tradeName
    Given path '/recipients/branches'
    And request
      """
      { 
        "cocNumber": "12345678" 
      }
      """
    When method post
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      { 
        "error": "validation/required-field-missing", 
        "description": "Descriptive Error Message", 
        "field": "tradeName" 
      }
      """

  Scenario: Add new branch with invalid cocNumber pattern
    Given path '/recipients/branches'
    And request
      """
      { 
        "cocNumber": "123", 
        "tradeName": "KarateMart" 
      }
      """
    When method post
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      { 
        "error": "validation/cocNumber-pattern", 
        "description": "Descriptive Error Message", 
        "value": "123", 
        "field": "cocNumber", 
        "schema_field": "cocNumber" 
      }
      """

  Scenario: Add new branch without authorization
    Given path '/recipients/branches'
    And request
      """
      { 
        "cocNumber": "12345678", 
        "tradeName": "KarateMart" 
      }
      """
    And header ApiKeyAuth = ''
    When method post
    Then status 401
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      { 
        "error": "error/code", 
        "description": "Descriptive Error Message" 
      }
      """
