# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /recipients/branches/{id}/registrations_get for http method type GET 
# RoostTestHash=49b35fa9c1
# 
# 

# ********RoostGPT********
Feature: Recipient Branch Registrations API Endpoint Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Successfully retrieve recipient branch registrations with valid parameters
    Given path 'recipients/branches/', <id>, '/registrations'
    And param credential-url = <credential-url>
    And param size = <size>
    And param offset = <offset>
    And header ApiKeyAuth = karate.properties['AUTH_TOKEN']
    When method get
    Then status 200
    And match response contains { total: '#number', registrations: '#array' }
    And match each response.registrations[*] contains { id: '#uuid', startDate: '#string', status: '#string', credentialUrl: '#regex[\\w+:(\\/?\\/?)[^\\s]+$]' }
    And match responseHeaders contains { api-version: '#string', page-size: '#number', page-offset: '#number' }

    Examples:
      | read('recipients_branches_id_registrations_get.csv') |

  Scenario: Attempt to retrieve recipient branch registrations with invalid ID
    Given path 'recipients/branches/invalid-uuid/registrations'
    And header ApiKeyAuth = karate.properties['AUTH_TOKEN']
    When method get
    Then status 400
    And match response contains { error: '#string', description: '#string' }
    And match responseHeaders contains { api-version: '#string' }

  Scenario: Retrieve recipient branch registrations without authentication
    Given path 'recipients/branches/d290f1ee-6c54-4b01-90e6-d701748f0851/registrations'
    When method get
    Then status 401
    And match response contains { error: '#string', description: '#string' }
    And match responseHeaders contains { api-version: '#string' }
