# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /recipients/branches/{id}_delete for http method type DELETE 
# RoostTestHash=1ce4bf6e3c
# 
# 

# ********RoostGPT********
Feature: Recipient Branch API endpoint tests

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario Outline: Get recipient branch details with valid UUID
    Given path 'recipients/branches', <id>
    When method get
    Then status 200
    And match header api-version == '1.0.0'
    And match response contains
      """
      { 
        id: '#uuid'
      }
      """

    Examples:
      | read('recipients_branches_id_delete.csv') |

  Scenario: Get recipient branch details with invalid UUID
    Given path 'recipients/branches', 'invalid-uuid'
    When method get
    Then status 400
    And match header api-version == '1.0.0'
    And match response contains
      """
      { 
        error: '#string', 
        description: '#string'
      }
      """

  Scenario: Get recipient branch details without authorization
    * header ApiKeyAuth = null
    Given path 'recipients/branches', '123e4567-e89b-12d3-a456-426614174000'
    When method get
    Then status 401
    And match header api-version == '1.0.0'
    And match response contains
      """
      { 
        error: '#string', 
        description: '#string'
      }
      """
