# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /recipients/persons/{id}/registrations_post for http method type POST 
# RoostTestHash=0973c499e9
# 
# 

# ********RoostGPT********
Feature: Create new Registration for Recipient Person

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Create a new registration for a recipient person with valid data
    Given path 'recipients/persons/', <id>, '/registrations'
    And header ApiKeyAuth = authToken
    And request
      """
      { 
        reference: '#(reference)', 
        startDate: '#(startDate)', 
        endDate: '#(endDate)', 
        credentialUrl: '#(credentialUrl)' 
      }
      """
    When method post
    Then status 201
    And match header api-version == '1.0.0'
    And match header location != null
    And match response
      """
      { 
        id: '#uuid', 
        reference: '#string', 
        startDate: '#string', 
        endDate: '#string?', 
        status: '#string', 
        credentialUrl: '#string', 
        suspendedUntil: '#string?', 
        issuedAt: '#string?', 
        createdAt: '#string', 
        updatedAt: '#string' 
      }
      """

    Examples:
      | read('recipients_persons_id_registrations_post.csv') |

  Scenario: Create a new registration for a recipient person with missing required fields
    Given path 'recipients/persons/', 'e2ec88e9-7f3d-4b59-b213-9edf32c64534', '/registrations'
    And header ApiKeyAuth = authToken
    And request { startDate: '2021-01-01' }
    When method post
    Then status 400
    And match header api-version == '1.0.0'
    And match response
      """
      {
        error: 'error/code', 
        description: 'Descriptive Error Message'
      }
      """

  Scenario: Attempt to create a new registration without authentication
    Given path 'recipients/persons/', 'e2ec88e9-7f3d-4b59-b213-9edf32c64534', '/registrations'
    And request
      """
      { 
        reference: 'Ref-123', 
        startDate: '2021-01-01', 
        endDate: '2023-01-01', 
        credentialUrl: 'http://example.com/credentials/12345' 
      }
      """
    When method post
    Then status 401
    And match header api-version == '1.0.0'
    And match response
      """
      {
        error: 'error/code', 
        description: 'Descriptive Error Message'
      }
      """
