# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /registrations/{id}_get for http method type GET 
# RoostTestHash=299c116110
# 
# 

# ********RoostGPT********
Feature: Registrations API Feature

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario Outline: Get registration details with valid ID
    Given path 'registrations', '<id>'
    When method get
    Then status 200
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        id: '#uuid', 
        startDate: '#date', 
        createdAt: '#date-time', 
        updatedAt: '#date-time', 
        status: '#string', 
        credentialUrl: '#regex(\\w+:(\\/\\/?)[^\\s]+)'
      }
      """
    And match response.recipient ==
      """
      {
        id: '#uuid', 
        name: '#regex(^[\\p{L} .'-]{1,100}$)', 
        type: '#string'
      }
      """

    Examples:
      | read('registrations_id_get.csv') |

  Scenario: Get registration details with invalid ID results in Bad Request
    Given path 'registrations', 'invalid-uuid'
    When method get
    Then status 400
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        error: '#string', 
        description: '#string'
      }
      """

  Scenario: Get registration details without authorization results in Authentication Required
    * header ApiKeyAuth = null
    Given path 'registrations', '3fa85f64-5717-4562-b3fc-2c963f66afa6'
    When method get
    Then status 401
    And match responseHeaders contains { 'api-version': '#string' }
    And match response ==
      """
      {
        error: '#string', 
        description: '#string'
      }
      """
