# ********RoostGPT********

# Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /registrations/{id}_patch for http method type PATCH 
# RoostTestHash=c1b0bbc56b
# 
# 

# ********RoostGPT********
Feature: Test Registrations API Endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header ApiKeyAuth = authToken

  Scenario Outline: Update a registration with valid data
    Given path 'registrations', <id>
    And request
      """
      <requestBody>
      """
    When method PUT
    Then status 200
    And match responseHeaders['api-version'] == '1.0.0'
    And match response ==
      """
      <expectedResponse>
      """

    Examples:
      | read('registrations_id_patch.csv') |

  Scenario: Update a registration with invalid UUID
    Given path 'registrations', 'invalid-uuid'
    And request
      """
      { "reference": "Ref-123", "revoked": false }
      """
    When method PUT
    Then status 400
    And match responseHeaders['api-version'] == '1.0.0'
    And match response.error == '#string'
    And match response.description == '#string'

  Scenario: Update a registration without authentication
    Given path 'registrations', 'd290f1ee-6c54-4b01-90e6-d701748f0851'
    And request
      """
      { "reference": "Ref-123", "revoked": false }
      """
    And header ApiKeyAuth = ''
    When method PUT
    Then status 401
    And match responseHeaders['api-version'] == '1.0.0'
    And match response.error == '#string'
    And match response.description == '#string'
