// ********RoostGPT********
/*
Test generated by RoostGPT for test karteKnoteTest using AI Type Open AI and AI Model gpt-4-1106-preview

Test generated for /recipients/branches/{id}/registrations_get for http method type GET in rest-assured framework

RoostTestHash=28f6c35529


*/

// ********RoostGPT********
package com.learnk8s.RoostTest;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;
import java.util.Arrays;

public class recipientsBranchesIdRegistrationsGetTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @BeforeEach
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      String[] envVarsList = {"id"};
      envList = dataloader.load("src/test/java/com/learnk8s/RoostTest/recipients_branches_id_registrationsGetTest.csv", envVarsList);
    }

  
    @Test  
    public void recipientsBranchesIdRegistrationsGet_Test() throws JSONException {
        this.setUp();
        Integer testNumber = 1;
        for (Map<String, String> testData : envList) {
          RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "https://virtserver.swaggerhub.com/credentialregister/wallet/1.0.0";  
          JSONObject requestBodyObject = new JSONObject();
          if(testData.get("RequestBody") != null){
              requestBodyObject = new JSONObject(testData.get("RequestBody"));
          }
                Response responseObj = given()
				.queryParam("credential-url", testData.get("credential-url") != null ? testData.get("credential-url") : "")
				.queryParam("size", testData.get("size") != null ? testData.get("size") : "")
				.queryParam("offset", testData.get("offset") != null ? testData.get("offset") : "")
				.pathParam("id", testData.get("id") != null ? testData.get("id") : "")
				.header("Token", testData.get("Token"))
                .when()
                .get("/recipients/branches/{id}/registrations")  
                .then() 
                .extract().response(); 
              JsonPath response;
              String contentType = responseObj.getContentType();

              System.out.printf("Test Case %d: recipientsBranchesIdRegistrationsGet_Test \n", testNumber++);
              System.out.println("Request: GET /recipients/branches/{id}/registrations");
              System.out.println("Status Code: " + responseObj.statusCode());
              if (testData.get("statusCode") != null) {
                String statusCodeFromCSV = testData.get("statusCode");
                if (statusCodeFromCSV.contains("X")) {
                  MatcherAssert.assertThat(
                      "Expected a status code of category " + statusCodeFromCSV + ", but got "
                          + Integer.toString(responseObj.statusCode()) + " instead",
                      Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
                } else {
                  MatcherAssert.assertThat(
                      Integer.toString(responseObj.statusCode()), equalTo(statusCodeFromCSV));
                }
              } 
              				else {  
      List<Integer> expectedStatusCodes = Arrays.asList(200,400,401);
				MatcherAssert.assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
          }
				String stringifiedStatusCode = Integer.toString(responseObj.statusCode());
        switch(responseObj.statusCode()){
        
          case 200:
            stringifiedStatusCode = "200";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 400:
            stringifiedStatusCode = "400";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
          case 401:
            stringifiedStatusCode = "401";
            MatcherAssert.assertThat(contentType, equalTo("application/json"));
            break;
         
    }

      switch(Integer.toString(responseObj.statusCode()).charAt(0)){
      
    }

      
              if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
                String xmlResponse = responseObj.asString();
                JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
                JSONObject jsonData = jsonResponse.getJSONObject("xml");
                String jsonString = jsonData.toString();
                response = new JsonPath(jsonString);
        
              } else if(contentType.contains("application/json")){  
                response = responseObj.jsonPath(); 
              } else {
                System.out.println("Response content type found: "+contentType+", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
                continue;
              }
         
                if(stringifiedStatusCode.equals("200")){					System.out.println("Description: successful operation");
      
              if (response.get("total") != null) {
                  
                MatcherAssert.assertThat(response.get("total"), instanceOf(Integer.class));
              }
      
              if (response.get("registrations") != null) {
                        
                  for (int i = 0; i < response.getList("registrations").size(); i++) {      
              if (response.get("registrations["+ i +"].id") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].id"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].reference") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].reference"), instanceOf(String.class));  
                MatcherAssert.assertThat(response.getString("registrations["+ i +"].reference").length(), lessThanOrEqualTo(100));

              }
      
              if (response.get("registrations["+ i +"].startDate") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].startDate"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].endDate") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].endDate"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].status") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].status"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].credentialUrl") != null) {
                    
                MatcherAssert.assertThat(response.getString("registrations["+ i +"].credentialUrl"), matchesPattern("^\\w+:(\\/?\\/?)[^\\s]+$")); 
  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].credentialUrl"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].suspendedUntil") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].suspendedUntil"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].issuedAt") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].issuedAt"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].createdAt") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].createdAt"), instanceOf(String.class));
              }
      
              if (response.get("registrations["+ i +"].updatedAt") != null) {
                  
                MatcherAssert.assertThat(response.get("registrations["+ i +"].updatedAt"), instanceOf(String.class));
              }
        
                    }    
                MatcherAssert.assertThat(response.getList("registrations"), instanceOf(List.class));

              }
				}
if(stringifiedStatusCode.equals("400")){					System.out.println("Description: Bad Request");
      
              if (response.get("error") != null) {
                  
                MatcherAssert.assertThat(response.get("error"), instanceOf(String.class));
              }
      
              if (response.get("description") != null) {
                  
                MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));
              }
      
              if (response.get("error") != null) {
                    
                MatcherAssert.assertThat(response.getString("error"), matchesPattern("^validation/.*$")); 
  
                MatcherAssert.assertThat(response.get("error"), instanceOf(String.class));
              }
      
              if (response.get("description") != null) {
                  
                MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));
              }
      
              if (response.get("field") != null) {
                  
                MatcherAssert.assertThat(response.get("field"), instanceOf(String.class));
              }
      
              if (response.get("schema_field") != null) {
                  
                MatcherAssert.assertThat(response.get("schema_field"), instanceOf(String.class));
              }
				}
if(stringifiedStatusCode.equals("401")){					System.out.println("Description: Authentication Required");
      
              if (response.get("error") != null) {
                  
                MatcherAssert.assertThat(response.get("error"), instanceOf(String.class));
              }
      
              if (response.get("description") != null) {
                  
                MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));
              }
      
              if (response.get("error") != null) {
                    
                MatcherAssert.assertThat(response.getString("error"), matchesPattern("^validation/.*$")); 
  
                MatcherAssert.assertThat(response.get("error"), instanceOf(String.class));
              }
      
              if (response.get("description") != null) {
                  
                MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));
              }
      
              if (response.get("field") != null) {
                  
                MatcherAssert.assertThat(response.get("field"), instanceOf(String.class));
              }
      
              if (response.get("schema_field") != null) {
                  
                MatcherAssert.assertThat(response.get("schema_field"), instanceOf(String.class));
              }
				}


            }  
    }
}
